### ISSUE TITLE
Usage without mixins

### ISSUE THREAD

**Issue by josemarluedke** [ember-graphql/ember-apollo-client#139]
When using ES Classes and/or TypeScript, it is not the best approach to use mixins. I know is possible, using `class XYZ extends Component.extend(Mixin) { ...` but it would be nice to not have an alternative to using mixins.

**Comment by bgentry** [comment]
Any other ideas for how to track `watchQuery` subscriptions on a per route/component/object basis? And to auto-unsubscribe when the object is torn down?

**Comment by josemarluedke** [comment]
Great discussion about a similar subject on Ember Simple Auth: https://github.com/simplabs/ember-simple-auth/issues/1619

**Comment by mike-north** [comment]
Looking at the mixins in question, it doesn't seem all that difficult for those who want a more explicit "composition instead of inheritance" option. 

#### Example:
https://github.com/bgentry/ember-apollo-client/blob/5296032ff0b10ac3bd9bebf6cca8f56946c90929/addon/mixins/route-query-manager.js#L5-L8

99% of the complexity in this addon lives on the service, which is excellent. If you don't want to use the `RouteQueryManager` mixin, just inject the `service:apollo` yourself, and add the appropriate one-liners to your route (or a route base class).

For a first-class TS/ES6 approach, looks like the work would be:
- [ ] add a few acceptance tests (A route, component and object) to protect against regression. The main thing that could go wrong in the future is ordering setup/teardown of the apollo client w/ the rest of the setup/teardown logic. As it stands, I doubt it matters if you do the apollo work before or after `this._super(...arguments);` but that could change. Tests would alert us to that change.
- [ ] document the mixin-free approach -- effectively doing what the respective mixins do

**Comment by buschtoens** [comment]
I've never worked with ember-apollo-client before, but am currently evaluating it. This was one of the first problems that sprung to mind for me and I am happy to see, that this is already being discussed.

I couldn't put it better as https://github.com/simplabs/ember-simple-auth/issues/1619#issuecomment-424190629:

> I personally would like to see a decorator approach. I think it makes it explicit and easy to reason about.

Using a class decorator like `@withApollo` seems reasonably clean to me:

```ts
import Component from '@ember/component';
import { withApollo, QueryManager } from 'ember-apollo-client';

@withApollo
export default class ExampleComponent extends Component {
  apollo!: QueryManager;
}
```

One current drawback of decorators in TypeScript is that they cannot yet mutate the type signature (https://github.com/Microsoft/TypeScript/issues/4881), which forces the user to manually type the `apollo` property. This is only a temporary issue though.

Instead of making this a class decorator, we could also use a class property decorator, like:

```ts
import Component from '@ember/component';
import { queryManager, QueryManager } from 'ember-apollo-client';

export default class ExampleComponent extends Component {
  @queryManager apollo!: QueryManager;
}
```

This would be similar to how service injections work:

```ts
import Component from '@ember/component';
import RouterService from '@ember/routing/router-service';
import { service } from '@ember-decorators/service';

export default class ExampleComponent extends Component {
  @service router!: RouterService;
}
```

This would also logically couple the `QueryManager` "injection" to the property that is used as the target for the injection, meaning that user _could_ use a different property name, if they wanted to:

```ts
import Component from '@ember/component';
import { queryManager, QueryManager } from 'ember-apollo-client';

export default class ExampleComponent extends Component {
  @queryManager store!: QueryManager;
}
```

I don't know, if this is a good thing, but I like the symmetry with `@service` and that you can see at a glance what injection is provided by using the decorator.

Anyhow, another advantage is that we can use the same decorator for all types of objects, since the decorator can query the type of the decorated class.

**Comment by tchak** [comment]
I implemented queryManager macro on my fork if some of you are interested in trying it out and give feedback. cc @buschtoens 

https://github.com/tchak/ember-apollo-client/tree/drop-mixins

**Comment by josemarluedke** [comment]
@tchak That approach seems very interesting. I will give it a try this week and see how it goes.
