### ISSUE TITLE
ReferenceError: react is not defined

### ISSUE THREAD

**Issue by achambers** [ember-graphql/ember-apollo-client#389]
I just installed this addon (great work by the way) in an existing project and the mere installation of it has broken a (seemingly) unrelated part of our app. We use a lib for editing photos that uses React - https://www.npmjs.com/package/photoeditorsdk. When trying to use the photo editor we are presented with the "ReferenceError: react not defined" error.

I tracked the reason down to this code https://github.com/ember-graphql/ember-apollo-client/blob/c312b07ff43938d8b6ab1d80b3baff7c5e631458/index.js#L20-L22

Which was introduced in #365 .

I have confirmed that removing this webpack configuration restores my app back to a working state.

So, I'm wondering if anyone here has any guidance around how we might improve this addon so that it supports the use case where other addons that use React can continue to operate while still honouring the original intention of the PR that introduced the change.

**Comment by achambers** [comment]
@josemarluedke I see you're the one who contributed the referenced PR. Do you have any advice around this?

**Comment by josemarluedke** [comment]
@achambers We had added that for ensuring we didn't include react without needing it. Since then, I learned that if you import all apollo code from `@apollo/client/core` we should not get react included. That means we could remove that configuration. 

Could you open a PR removing that and reviewing our code to make sure we do all the imports from `@apollo/client/core`? 

Thank you.

**Comment by achambers** [comment]
Thanks for the update @josemarluedke. I'll take a look at that tomorrow.
